/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PopoverArrow: typeof import('reka-ui')['PopoverArrow']
    PopoverClose: typeof import('reka-ui')['PopoverClose']
    PopoverContent: typeof import('reka-ui')['PopoverContent']
    PopoverPortal: typeof import('reka-ui')['PopoverPortal']
    PopoverRoot: typeof import('reka-ui')['PopoverRoot']
    PopoverTrigger: typeof import('reka-ui')['PopoverTrigger']
    ProgressIndicator: typeof import('reka-ui')['ProgressIndicator']
    ProgressRoot: typeof import('reka-ui')['ProgressRoot']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const PopoverArrow: (typeof import('reka-ui'))['PopoverArrow']
  const PopoverClose: (typeof import('reka-ui'))['PopoverClose']
  const PopoverContent: (typeof import('reka-ui'))['PopoverContent']
  const PopoverPortal: (typeof import('reka-ui'))['PopoverPortal']
  const PopoverRoot: (typeof import('reka-ui'))['PopoverRoot']
  const PopoverTrigger: (typeof import('reka-ui'))['PopoverTrigger']
  const ProgressIndicator: (typeof import('reka-ui'))['ProgressIndicator']
  const ProgressRoot: (typeof import('reka-ui'))['ProgressRoot']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
}
